apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: voicecompanion
spec:
  template:
    metadata:
      annotations:
        # Increase as needed for image/music generation
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: voicecompanion-sa@hackathon-482302.iam.gserviceaccount.com
      containers:
        # Frontend (nginx) - receives traffic
        - name: frontend
          image: gcr.io/hackathon-482302/voicecompanion-frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
        # Backend API
        - name: backend
          image: gcr.io/hackathon-482302/voicecompanion-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: VERTEX_AI_LOCATION
              value: "us-central1"
            # Secrets (fill in with Secret Manager bindings if desired)
            # ElevenLabs
            - name: ELEVENLABS_API_KEY
              value: "__SET_IN_CLOUD_RUN__"
            # Gemini (if used)
            - name: GEMINI_API_KEY
              value: "__SET_IN_CLOUD_RUN__"
            - name: GOOGLE_CLOUD_hackathon-482302
              value: "hackathon-482302"


